### ISSUE TITLE
iOS device does not respond to connection request (iOS10.3.2)

### ISSUE THREAD

**Issue by harizhent** [dclelland/Gong#2]
It seems that connection is being dropped soon after MIDIClient connects to any kind of source.
iOS device is detected in Audio MIDI Setup directory and library notifies me of "Setup Change", but after that no notifications are coming.

**Comment by dclelland** [comment]
Could I ask for some more details please? What are you trying to connect to? Do you have a few screenshots?

**Comment by harizhent** [comment]
At the moment i don't have it - but i can make it.  I have compiled and ran project with your library. Ran it on iPad (iOS10.3.2) and connected to MacBook. MacBook had MidiSetup running and in there i can see my iPad as MIDI "live routing node".  After i connect iPad to MacBook - i can send few notes and then iPad looses its connection (it does not loose network, just midi connection). Later i will provide screenshots if needed. I kinda believe that it is Apple bug, i have tried many midi lib's - they were doing the same.

**Comment by designerfuzzi** [comment]
as of your problem is with many lib's it could be classic problem, caused by usb connector/cable quality and the apple usb loading quantity process handling. Even a tiny drop caused by this process stops and republishes the connection but you loose the hosting in midi setup between mac and ios. If your loading status sign of the iOS device is flickering also it may help to load the devices battery to more than 70%, best to 100%. And make a reset of location and time settings in general setup, which causes your mac to ask for validation of the device connection again. After that the protocol works usually fine again, if it was not a probably weak cable itself.

knowing this from developing a midi c# lib for sequencing any kind of midi , where performance is the most important part of course. Was not happy with all those libs out there that limit in some point the power of coremidi. So ended up here, maybe comparing this nicely swift coded lib to my own work.
